# Generated by Django 5.2.4 on 2025-07-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='_likes',
        ),
        migrations.AddField(
            model_name='video',
            name='_views',
            field=models.SmallIntegerField(db_column='views', default=0),
        ),
    ]
