# Generated by Django 5.2.4 on 2025-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
