# Generated by Django 5.2.4 on 2025-07-18 14:23

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to=videos.models.images_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=videos.models.videos_upload_to),
        ),
    ]
