# Generated by Django 5.2.4 on 2025-07-19 12:03

import cloudinary_storage.storage
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_image_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=videos.models.images_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=videos.models.videos_upload_to),
        ),
    ]
