# Generated by Django 5.2.4 on 2025-07-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
