# Generated by Django 5.2.4 on 2025-07-19 12:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_image_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
