# Generated by Django 5.2.4 on 2025-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
