# Generated by Django 5.2.4 on 2025-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video__likes_video__views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='_views',
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.SmallIntegerField(default=0),
        ),
    ]
