# Generated by Django 5.2.4 on 2025-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video__views_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
